# Generated by Django 4.2 on 2023-05-03 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdepartmentmapper',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sms.userprofile'),
        ),
        migrations.AlterField(
            model_name='teachersubjectmapper',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sms.userprofile'),
        ),
    ]
