# Generated by Django 4.2 on 2023-05-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_alter_studentdepartmentmapper_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_define_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='User ID'),
        ),
    ]
